# [지도 학습]

## 1. K-Nearest Neighbor

In [1]:
# 라이브러리 호출 및 데이터 준비
import numpy as np # 벡터 및 행렬 연산 처리를 위한 라이브러리
import matplotlib.pyplot as plt # 데이터를 차트나 플롯으로 그려 주는 라이브러리
import pandas as pd # 데이터 분석 및 조작을 위한 라이브러리
from sklearn import metrics # 모델 성능 평가

names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class'] # 데이터셋에 컬럼 할당

dataset = pd.read_csv('./data/iris.data', names=names)

In [2]:
dataset

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
# 훈련과 테스트 데이터셋으로 분리
X = dataset.iloc[:, :-1].values # 모든 행을 사용, 컬럼은 뒤에서 하나를 뺀 값을 가져옴
y = dataset.iloc[:, 4].values # 모든 행을 사용, 5번 째 (4번 째 인덱스) 값만 가져와서 Y에 저장

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) # X(train/test) / Y(train/test)

In [4]:
X_train

array([[6.7, 2.5, 5.8, 1.8],
       [4.4, 3. , 1.3, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [5.9, 3. , 5.1, 1.8],
       [5.4, 3.4, 1.5, 0.4],
       [4.9, 3. , 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [5. , 3.5, 1.3, 0.3],
       [5.8, 2.8, 5.1, 2.4],
       [7.2, 3.6, 6.1, 2.5],
       [5.5, 2.6, 4.4, 1.2],
       [5. , 2.3, 3.3, 1. ],
       [4.8, 3.4, 1.9, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [6.1, 2.9, 4.7, 1.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.6, 2.9, 4.6, 1.3],
       [4.8, 3.4, 1.6, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [5. , 2. , 3.5, 1. ],
       [5.1, 3.8, 1.6, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [4.8, 3.1, 1.6, 0.2],
       [6. , 2

In [5]:
X_test

array([[4.9, 3.1, 1.5, 0.1],
       [7.7, 3.8, 6.7, 2.2],
       [6.4, 3.1, 5.5, 1.8],
       [7.7, 3. , 6.1, 2.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5. , 3. , 1.6, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.5, 2.4, 3.8, 1.1],
       [7.4, 2.8, 6.1, 1.9],
       [6.1, 3. , 4.9, 1.8],
       [6.3, 2.5, 4.9, 1.5],
       [6.4, 2.8, 5.6, 2.1],
       [5.7, 2.6, 3.5, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 2.3, 4.4, 1.3],
       [5.8, 2.6, 4. , 1.2],
       [6.5, 3. , 5.2, 2. ],
       [6.8, 2.8, 4.8, 1.4],
       [4.5, 2.3, 1.3, 0.3],
       [6.7, 3.1, 4.4, 1.4],
       [6.7, 3. , 5. , 1.7],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3. , 5.2, 2.3],
       [5.1, 3.5, 1.4, 0.2],
       [7.6, 3. , 6.6, 2.1],
       [5. , 3.5, 1.6, 0.6]])

In [6]:
y_train

array(['Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-v

In [7]:
y_test

array(['Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa'], dtype=object)

In [8]:
from sklearn.preprocessing import StandardScaler
s = StandardScaler() # 특성 스케일링, 평균이 0, 표준편차가 1이 되도록 변환
X_train = s.fit(X_train).transform(X_train) # 훈련 데이터를 스케일링 처리
X_test = s.fit_transform(X_test) # 테스트 데이터를 스케일링 처리

In [9]:
X_train

array([[ 1.10933199, -1.28648106,  1.1639349 ,  0.77162614],
       [-1.80385192, -0.15467954, -1.42898939, -1.33880433],
       [ 0.47603114, -0.38103984,  0.29962681,  0.11211662],
       [-0.91723073,  0.97712198, -1.37136885, -1.20690242],
       [-0.41059005, -1.28648106,  0.12676519,  0.11211662],
       [-0.41059005,  2.56164411, -1.37136885, -1.33880433],
       [ 1.74263284,  0.29804107,  1.27917598,  0.77162614],
       [ 0.09605063, -0.15467954,  0.76059113,  0.77162614],
       [-0.53725022,  0.75076167, -1.31374831, -1.07500052],
       [-1.17055107, -0.15467954, -1.37136885, -1.33880433],
       [ 0.2227108 , -0.15467954,  0.58772951,  0.77162614],
       [-0.28392988, -0.60740015,  0.64535005,  1.03542995],
       [-1.0438909 ,  0.97712198, -1.42898939, -1.20690242],
       [-0.03060954, -0.60740015,  0.76059113,  1.56303756],
       [ 1.74263284,  1.20348228,  1.33679652,  1.69493947],
       [-0.41059005, -1.06012076,  0.35724735, -0.01978529],
       [-1.0438909 , -1.

In [10]:
X_test

array([[-1.07223969,  0.26770932, -1.17773982, -1.3473168 ],
       [ 1.87116338,  2.0812241 ,  1.64016528,  1.39077863],
       [ 0.50458338,  0.26770932,  0.98987948,  0.86923665],
       [ 1.87116338,  0.00863578,  1.31502238,  1.52116413],
       [-1.3876043 ,  0.52678286, -1.23193031, -1.2169313 ],
       [-1.3876043 ,  1.04492994, -1.23193031, -1.08654581],
       [-0.546632  ,  1.04492994, -1.06935886, -1.2169313 ],
       [-0.96711815,  0.00863578, -1.12354934, -1.2169313 ],
       [-1.07223969,  0.26770932, -1.17773982, -1.3473168 ],
       [-0.44151046, -1.54580546,  0.06864128, -0.04346183],
       [ 1.55579877, -0.5095113 ,  1.31502238,  0.99962214],
       [ 0.18921877,  0.00863578,  0.66473659,  0.86923665],
       [ 0.39946185, -1.28673192,  0.66473659,  0.47808016],
       [ 0.50458338, -0.5095113 ,  1.04406997,  1.26039314],
       [-0.23126738, -1.02765838, -0.09393017, -0.17384733],
       [-0.75687508,  1.04492994, -1.23193031, -1.2169313 ],
       [-0.23126738,  0.

In [11]:
# 모델 생성 및 훈련
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=50) # K=50인 K-NN모델 생성
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=50)

In [12]:
knn

KNeighborsClassifier(n_neighbors=50)

In [13]:
from sklearn.metrics import accuracy_score
y_pred = knn.predict(X_test)
print("정확도: {}".format(accuracy_score(y_test, y_pred)))

정확도: 0.9333333333333333


In [15]:
y_test

array(['Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa'], dtype=object)

In [14]:
y_pred

array(['Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa'], dtype=object)

In [16]:
# 최적의 k값 찾기
k = 10
acc_array = np.zeros(k)

for k in np.arange(1, k+1, 1): # k는 1에서 10까지의 숫자를 가짐
    classifier = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train) # for문 돌면서 k값 변경
    y_pred = classifier.predict(X_test)
    acc = metrics.accuracy_score(y_test, y_pred)
    acc_array[k-1] = acc
    
max_acc = np.amax(acc_array, axis=0) # 행에서 가장 큰 값을 리턴 (2차원일 때 axis=0이면 행, axis=1이면 컬럼 별로 값 리턴해줌)
acc_list = list(acc_array)
k = acc_list.index(max_acc)
print("정확도", max_acc, "으로 최적의 k는", k+1, "입니다.")

정확도 0.9333333333333333 으로 최적의 k는 2 입니다.
