In [3]:
import pandas as pd
import torch

data = pd.read_csv('./data/class2.csv')
data

Unnamed: 0      id tissue class class2      x      y      r
0           0  mdb000      C  CIRC      N  535.0  475.0  192.0
1           1  mdb001      A  CIRA      N  433.0  268.0   58.0
2           2  mdb002      A  CIRA      I    NaN    NaN    NaN
3           3  mdb003      C  CIRC      B    NaN    NaN    NaN
4           4  mdb004      F  CIRF      I  488.0  145.0   29.0
5           5  mdb005      F  CIRF      B  544.0  178.0   26.0

In [4]:
data['x'].values

array([535., 433.,  nan,  nan, 488., 544.])

In [5]:
type(data['x'].values) # numpy.ndarray

numpy.ndarray

In [ ]:
#------------------------------------------------------#
# ndarray를 tensor.from_numpy #
#------------------------------------------------------#

In [15]:
torch.from_numpy(data['x'].values)

tensor([535., 433.,  nan,  nan, 488., 544.], dtype=torch.float64)

In [16]:
torch.from_numpy(data['x'].values).shape

torch.Size([6])

In [ ]:
#------------------------------------------------------#
# ndarray를 tensor.from_numpy한 다음, unsqueeze(0) 시도 #
#------------------------------------------------------#

In [18]:
torch.from_numpy(data['x'].values).unsqueeze(0)

tensor([[535., 433.,  nan,  nan, 488., 544.]], dtype=torch.float64)

In [20]:
torch.from_numpy(data['x'].values).unsqueeze(0).shape

torch.Size([1, 6])

In [ ]:
#------------------------------------------------------#
# ndarray를 tensor.from_numpy한 다음, unsqueeze(1) 시도 #
#------------------------------------------------------#

In [13]:
torch.from_numpy(data['x'].values).unsqueeze(1)

tensor([[535.],
        [433.],
        [ nan],
        [ nan],
        [488.],
        [544.]], dtype=torch.float64)

In [17]:
torch.from_numpy(data['x'].values).unsqueeze(1).shape

torch.Size([6, 1])

In [ ]:
#------------------------------------------------------#
# ndarray를 tensor.from_numpy한 다음, unsqueeze(-1) 시도 #
#------------------------------------------------------#

In [21]:
torch.from_numpy(data['x'].values).unsqueeze(-1)

tensor([[535.],
        [433.],
        [ nan],
        [ nan],
        [488.],
        [544.]], dtype=torch.float64)

In [22]:
torch.from_numpy(data['x'].values).unsqueeze(-1).shape

torch.Size([6, 1])

In [7]:
x = torch.from_numpy(data['x'].values).unsqueeze(dim=1).float()
x

tensor([[535.],
        [433.],
        [ nan],
        [ nan],
        [488.],
        [544.]])

In [23]:
x.shape

torch.Size([6, 1])

In [8]:
y = torch.from_numpy(data['y'].values).unsqueeze(dim=1).float()
y

tensor([[475.],
        [268.],
        [ nan],
        [ nan],
        [145.],
        [178.]])