# 손실 함수

## 1. MSE (평균 제곱 오차)

In [1]:
import torch

In [2]:
loss_fn = torch.nn.MSELoss(reduction='sum')
y_pred = model(x)
loss = loss_fn(y_pred, y)

NameError: name 'model' is not defined

## 2. Cross Entropy Error (크로스 엔트로피 오차)

In [3]:
torch.randn(5, 6, requires_grad=True)

tensor([[ 1.1974, -0.4056, -0.8080,  0.6714,  0.2088, -1.7610],
        [ 2.6216, -0.3896, -0.5011, -0.0273,  1.1680,  0.3490],
        [-1.3229,  1.0128,  0.8658, -0.2988, -0.8793, -0.0406],
        [-2.3097,  0.1714,  0.2672, -0.5914, -0.3387, -1.3528],
        [-0.3892,  0.3403, -0.1653, -0.7678, -1.1788,  0.2314]],
       requires_grad=True)

In [4]:
torch.randn(5, 6, requires_grad=False)

tensor([[ 0.5988,  0.5746,  0.0920, -0.2263,  2.4692,  1.7082],
        [-1.0304,  0.6744,  0.8458, -0.9966, -0.9970, -0.6142],
        [ 0.4996, -0.1412,  0.6513,  0.2705,  0.2872, -1.9879],
        [ 1.3199, -1.4761,  0.5385,  0.3447, -0.4998,  0.2014],
        [-1.1946, -0.1242, -0.3156, -1.8000, -0.1058, -1.1874]])

In [6]:
torch.empty(3, dtype=torch.long).random_(5)

tensor([3, 0, 3])

In [7]:
torch.empty(3, dtype=torch.long)

tensor([7002363436420038656, 7004563293792121701, 7161117467399513648])

In [8]:
torch.empty(3, dtype=torch.long).random_(1)

tensor([0, 0, 0])

In [9]:
torch.empty(3, dtype=torch.long).random_(500)

tensor([456, 489,   3])

In [12]:
loss = torch.nn.CrossEntropyLoss()
input = torch.randn(3, 6, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
output.backward()

In [13]:
output

tensor(1.9541, grad_fn=<NllLossBackward>)

In [14]:
loss

CrossEntropyLoss()

In [15]:
input

tensor([[ 1.3435, -1.7790,  1.4861,  1.1509, -2.1480, -0.0745],
        [ 0.3730,  0.7182, -0.2798, -0.1027,  0.1489, -0.8966],
        [ 0.0895,  0.8121,  1.1822, -0.5955, -0.2844,  0.1699]],
       requires_grad=True)

In [17]:
target

tensor([2, 3, 3])